### ISSUE TITLE
log print to cell output

### ISSUE THREAD

**Issue by LukaPitamic** [denphi/jupyterlab-floatview#3]
JupyterLab (v1.1.1) is printing log message into cell output. This behavior appeared with upgrading JupyterLab to v 1.1.1. If I remove `from floatview import Floatview` then everything works as it should and log message only appears in log file - not additionally in cell output.  

Here's what I mean:
![image](https://user-images.githubusercontent.com/34914144/64475098-84bb0400-d16d-11e9-8d57-667c05b5ffd6.png)

**Comment by LukaPitamic** [comment]
...and even `%%capture` doesn't seam to suppress the log output to cell

**Comment by denphi** [comment]
This issue is created by the glueviz library when loaded by floatview, glueviz adds a new stream handler to the global logging manager (logging.root).

If you clean the handlers list after importing floatview you can bypass the problem.

```
 import floatview
 logging.root.removeHandler(logging.root.handlers[0])
```

I will try to find for a cleaner solution on the next release

**Comment by LukaPitamic** [comment]
This solves the problem, thank you!
